config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :dudes
  resources :bears do
  end

end

app/models/bear.rb
class Bear < ActiveRecord::Base
  has_many :honeys

  accepts_nested_attributes_for :honeys, allow_destroy: true
end

app/models/honey.rb
class Honey < ActiveRecord::Base
  belongs_to :bear
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/bears_controller.rb
class BearsController < ApplicationController
  before_action :set_bear, only: [:show, :edit, :update, :destroy]

  # GET /bears
  # GET /bears.json
  def index
    @bears = Bear.all
  end

  # GET /bears/1
  # GET /bears/1.json
  def show
  end

  # GET /bears/new
  def new
    @bear = Bear.new
  end

  # GET /bears/1/edit
  def edit
  end

  # POST /bears
  # POST /bears.json
  def create
    @bear = Bear.new(bear_params)

    respond_to do |format|
      if @bear.save
        format.html { redirect_to @bear, notice: 'Bear was successfully created.' }
        format.json { render :show, status: :created, location: @bear }
      else
        format.html { render :new }
        format.json { render json: @bear.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bears/1
  # PATCH/PUT /bears/1.json
  def update
    respond_to do |format|
      if @bear.update(bear_params)
        format.html { redirect_to @bear, notice: 'Bear was successfully updated.' }
        format.json { render :show, status: :ok, location: @bear }
      else
        format.html { render :edit }
        format.json { render json: @bear.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bears/1
  # DELETE /bears/1.json
  def destroy
    @bear.destroy
    respond_to do |format|
      format.html { redirect_to bears_url, notice: 'Bear was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bear
      @bear = Bear.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bear_params
      params.require(:bear).permit(
        :name, 
        honeys_attributes: [:id, :name, :_destroy])
    end
end

app/controllers/dudes_controller.rb
class DudesController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bears_helper.rb
module BearsHelper
end

app/helpers/dudes_helper.rb
module DudesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/bears/_form.html.haml
= nested_form_for @bear do |f|
  - if @bear.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bear.errors.count, "error")} prohibited this bear from being saved:"
      %ul
        - @bear.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.fields_for :honeys do |honey_form|
      = honey_form.text_field :name
      = honey_form.link_to_remove "Remove this honey"
    %p= f.link_to_add "Add a honey", :honeys
  .actions
    = f.submit 'Save'

app/views/bears/_navbar.html.haml
= render 'layouts/navbar'

app/views/bears/edit.html.haml
%h1 Editing bear

= render 'form'

= link_to 'Show', @bear
\|
= link_to 'Back', bears_path

app/views/bears/index.html.haml
%h1 Listing bears

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @bears.each do |bear|
    %tr
      %td= bear.name
      %td= link_to 'Show', bear
      %td= link_to 'Edit', edit_bear_path(bear)
      %td= link_to 'Destroy', bear, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Bear', new_bear_path

app/views/bears/new.html.haml
%h1 New bear

= render 'form'

= link_to 'Back', bears_path

app/views/bears/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @bear.name
%p
  Types of Honey:
  %ul
    - @bear.honeys.each do |honey|
      %li= honey.name

= link_to 'Edit', edit_bear_path(@bear)
\|
= link_to 'Back', bears_path

app/views/dudes/_navbar.html.haml
%li= link_to "Batman", "/path1"
%li= link_to "Superman", "/path2"
%li= link_to "Spiderman", "/path3"  

app/views/home/_navbar.html.haml
= render 'layouts/navbar'

app/views/home/index.html.haml
= link_to "Dudes", dudes_path
= link_to "Bears", bears_path

Some content.
= text_field_tag '', '', class: "this_is_a_dude_class"
= link_to "Open Dialog", "javascript:void(0);", class: "open_dialog"

%a{href: "#brian_is_cool"} Brian is cool.

%div.these_are_going_to_be_tabs
  %ul
    %li
      %a{href: '#tab1'} Tab 1
    %li
      %a{href: '#tab2'} Tab 2
    %li
      %a{href: '#tab3'} Tab 3
  %div#tab1
    This is the first tab's content.
  %div#tab2
    This is the second tab's content.
  %div#tab3
    This is the third tab's content.

= text_field_tag "q", "", class: "autocomplete_1"


%div.new_accordion
  %h3
    %a{href: '#'} Sweet Content.
  %div
    THis is some sweet content.
  %h3
    %a{href: '#'} Batman
  %div
    Batman is the coolest superhero. Everyone else is wrong.

Patient 0
%a Show
%br
Patient 1
%a Show
%br
Patient 2
%a Show
%br
Patient 3
%a Show
%br

#brian_is_cool
  Brian is WAY cool.


.droppable
  .draggable
    Kevin is super cool.

  .draggable
    Kevin is WAY cool.

.sortable
  %ul
    %li Kevin
    %li Preston
    %li Brian
    %li Gene
    %li Rich






%div.dialog_thing
  Some content goes here. Brian, you're cool. Preston, you're cool too. So on and so forth.

app/views/layouts/_navbar.html.haml
%li= link_to "Link 1", "/path1"
%li= link_to "Link 2", "/path2"
%li= link_to "Link 3", "/path3"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title BootstrapJqueryUI
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") BootstrapJqueryUI
          .container.nav-collapse
            %ul.nav
              = render 'navbar'
    .container
      .row
        = yield

app/views/layouts/theme.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "BootstrapJqueryUI"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") BootstrapJqueryUI
          .container.nav-collapse
            %ul.nav
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"

    .container

      .row
        .span9
          = bootstrap_flash
          = yield
        .span3
          .well.sidebar-nav
            %h3 Sidebar
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"
    
      %footer
        %p &copy; Company 2014